### ISSUE TITLE
Unable to save model with BELONGS_TO association that does not allow a null foreign key

### ISSUE THREAD

**Issue by HackedByChinese** [creativecuriositystudio/squell#2]
**Environment**

* Squell@0.9.0
* Sequelize@4.0.0-2
* Typescript@2.3.2.

**Actual Behavior**
When saving a model with a BELONGS_TO association that does not `allowNull` in the foreign key on the inverse side of the association, I get the following exception:

```
     notNull Violation: list_id cannot be null
  Error
      at new ValidationError (node_modules/modelsafe/src/validation.ts:102:18)
      at coerceValidationError (node_modules/squell/src/query.ts:81:16)
      at Query.<anonymous> (node_modules/squell/src/query.ts:632:33)
      at Generator.next (<anonymous>)
      at node_modules/squell/dist/query.js:7:71
      at new wrappedPromise (node_modules/async-listener/index.js:408:16)
      at __awaiter (node_modules/squell/dist/query.js:3:12)
      at Promise.resolve.internalModel.create.catch (node_modules/squell/src/query.ts:631:78)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at node_modules/bluebird/js/release/catch_filter.js:17:41
      at node_modules/continuation-local-storage/context.js:84:17
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
      at Immediate.<anonymous> (node_modules/async-listener/glue.js:188:31)
  caused by SequelizeBaseError: null
      at Promise.all.then (node_modules/sequelize/lib/instance-validator.js:69:15)
      at node_modules/continuation-local-storage/context.js:84:17
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:126:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:144:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
      at Immediate.<anonymous> (node_modules/async-listener/glue.js:188:31)

```

**Expected Behavior**
Save the model with the BELONGS_TO association and use the value specified in the `include()` statement.

**Description**

I have a simple schema where there is a one-to-many relationship between a List and its ListItems. Each ListItem must have a valid FK to the List it belongs to. 

```
@modelsafe.model()
export class List extends @modelsafe.Model {
  @squell.attr({ autoIncrement: true })
  @modelsafe.attr(modelsafe.BIGINT, { primary: true })
  public id: number;

  @modelsafe.attr(modelsafe.STRING)
  public name: string;

  @squell.assoc({ foreignKey: { allowNull: false })
  @modelsafe.assoc(modelsafe.HAS_MANY, () => ListItem)
  public listItems: ListItem[];
}

@modelsafe.model()
export class ListItem extends modelsafe.Model {
  @squell.attr({ autoIncrement: true })
  @modelsafe.attr(modelsafe.BIGINT, { primary: true })
  public id: number;

  @squell.assoc({ foreignKey: { allowNull: false }})
  @modelsafe.assoc(modelsafe.BELONGS_TO, List)
  public list: List;

  @modelsafe.attr(modelsafe.STRING)
  public value: string;
}

export const db = new squell.Database('sqlite::memory:', {
   dialect: 'sqlite',
   define: {
     freezeTableName: true,
     timestamps: true,
     underscored: true,
     underscoredAll: true
   }
});
```

Here is a simple case where I create a `ListItem` that includes the parent `List`.

```
let list = new List({id: 1, name: 'Test List' });
await db.query(List).create(list);

let item = new ListItem({value: 'testing' });
item.list = {id: 1} as List;

await db.query(ListItem)
   .include(List, item => item.list)
   .create(item); // throws here
```

**Workaround**
If I remove the `@squell.assoc({ foreignKey: { allowNull: false }})` from `List` (it seems to ignore the attribute on `ListItem` in this case), it works, but of course the FK must allow null which I don't want.

**Misc**
I'm also not sure how to change the name of a property on the belongsTo model to something else, say `ListItem.parent` instead of list. I can get Sequelize to use the right column if I add  `@squell.assoc({ foreignKey: {field: 'parent_id' }})` on both sides of the association, but with `allowNull: true` it gives the error above and still references the field `list_id` instead of `parent_id`. I suppose that's another issue altogether, though.

**Comment by z0w0** [comment]
Hey thanks for the issue & PR.

Does the pull request you submitted also resolve your notes under section `Misc`? If not please open a new issue, as that behaviour should indeed be working - so that's a bug..

**Comment by HackedByChinese** [comment]
Yeah, that combined with the fact that using the name parameter for the
foreignKey parameter (or just passing a string for foreignKey) will address
the issue. I do have this set up and working in the PR.

Thanks for these libraries. Working with Sequelize in Typescript is a pain!
